### ISSUE TITLE
Build a layout validator 

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/open-physiology-viewer#120]
We need to build a validator based on known  test cases.

**Comment by enicolasgomez** [comment]
@jrmartin @SimaoBolota-MetaCell been doing some research and I think that the best way to achieve this is:

- launch puppeteer instance (headless chrome with API) with a model to load parameter
- produce a 2 color image from the HTML5 Canvas
- produce a hash from the 2 color image

do this for a code base considered stable to obtain the hashes for each test model

- repeat above process on a feature branch
- compare hashes similarity for the ones obtained from the stable branch and obtain a % diff
- fail those which are below a predefined threshold
- use jtest to create the testing harness 

as the process is processing intensive is probably no a good idea to integrate this to CI/CD

also, I think that for doing this it will be a good idea to merge #31 (3D Scene consuming 100% CPU resources issue fix (2) #152) to keep the process as lean as possible.

We can go over this on today's meeting

**Comment by enicolasgomez** [comment]
@jrmartin PR ready:
https://github.com/MetaCell/open-physiology-viewer/pull/134
