### ISSUE TITLE
UI Tests

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/open-physiology-viewer#121]
1) Get familiar with application
Application : https://open-physiology-viewer-tgbugs.surge.sh/

Instructions to load model:
-  Download json model from here https://raw.githubusercontent.com/MetaCell/apinatomy-models/metacell-models-update/models/dev-layout-conn/source/dev-layout-conn.json
- Load model by following instructions in this video. [here](https://images.zenhubusercontent.com/368226937/d956702a-0c82-4570-9863-24b4f1da9ad2/demo_load_model.mp4).

**Comment by SimaoBolota-MetaCell** [comment]
Linked to this trello card in the QA Board -> https://trello.com/c/De4bEohM
