### ISSUE TITLE
Create Tag from Develop Branch 

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/open-physiology-viewer#152]
We need to save the work in the develop branch, before we merge master branch into it.

**Comment by ddelpiano** [comment]
just had a chat about this during the board grooming with @jrmartin , we need @enicolasgomez input here so that we can decide once for all what gitflow to follow here and then present the proposal to them if it involves changing for the client (single repo and we abandon the metacell one?).

**Comment by jrmartin** [comment]
- Develop branch is now a copy of master branch, both are sync.
- The tests created by Simao have been merged to develop branch.
- The old develop branch was saved under branch 'old_develop'
