### ISSUE TITLE
Revisit  function fromJSONGenerated in converter.js

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/open-physiology-viewer#162]
- [x] Check out our master branch once this other issue is closed. https://github.com/MetaCell/open-physiology-viewer/issues/161
- [x]  Update fromJSONGenerated converter, you'll need to revisit this issue https://github.com/MetaCell/open-physiology-viewer/issues/136. Feature/136 branch was already merged into our master branch, please don't use that branch anymore as is outdated.
- [x]  Create a unit test for the fromJSONGenerated method to find out when it fails easier.

**Comment by jrmartin** [comment]
@ddelpiano Master branch has been merged, you can start working on this when you have a chance.

**Comment by ddelpiano** [comment]
tests are already in place since day 1 the converter was created (fyi).
