### ISSUE TITLE
Enable Neurulated Neuron

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/open-physiology-viewer#166]
Following specifications defined here https://docs.google.com/document/d/1X_v5Zjf9iQnaAhrIEQBd5odi4TE6DxO2E06CUqcI3wI/edit and further expanded in the agenda .

We need to create the functionality to toggle on and off Neurulated groups. 
- If a neurulated group is turned on, everything not related to the Neuron will be turned off. Meaning all scaffold map where the Neuron is not anchored or hosted by. Only the edges, nodes and housing Lyphs of the toggle neuron will be visible.

**Comment by ddelpiano** [comment]
duplicate of #180
