### ISSUE TITLE
Fix Broken Layout

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/open-physiology-viewer#173]
Broken layout, issue is opened here with details:
https://github.com/open-physiology/open-physiology-viewer/issues/205

**Comment by ddelpiano** [comment]
Testing this from the latest master and I can see it's rendered differently from the image attached in the card mentioned.

![scrnli_01_09_2022_13-50-41.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/a280ea50-ab0e-4374-a817-51399b79310f)
![scrnli_01_09_2022_13-50-43.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/754b4012-eb76-4907-b733-f5eadf80d6fe)

Is this fine? from what I can see (screenshots attached) all the lyphs are attached to the chain, not sure how to reproduce this issue (using the same model in the top bar of the screenshot provided in the issue mentioned and enabling the same group).
