### ISSUE TITLE
Resume codefresh deployment

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/open-physiology-viewer#184]
Just noticed that we already worked on having an codefresh deployment for apinatomy but it got lost due to the rebase that we had to do from the client repo - could we please resume this? 
Might just work reopening a PR from that feature branch against the latest development.

https://app.zenhub.com/workspaces/apinatomy-60ca921cef28f400109b6554/issues/metacell/open-physiology-viewer/115

Thanks

**Comment by ddelpiano** [comment]
build running but not working, worth checking the node environment used by docker for the build since that might be the problem https://g.codefresh.io/build/63500ef03c8757fb06db2369?step=build&tab=output&logs=terminal

**Comment by SimaoBolota-MetaCell** [comment]
It should be ```FROM node:16 as base``` right? 
<img width="997" alt="image (14)" src="https://user-images.githubusercontent.com/99416933/197223507-3fb8632a-9355-4346-b6b6-c05e54470f74.png">
