### ISSUE TITLE
Match mouse interaction to well known tools

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/open-physiology-viewer#22]
We need to look into other tools with 3D object manipulations in a canvas, and emulate the mouse interaction of those tools. We need to keep in mind current functionality, plus the new features of the authoring tool, which is a work in progress.

TODO List:

- [ x ] Analyze similar tools and find out how user interact with the mouse in those tools
- [ x ] Propose new mouse interaction .
- [ ] Peer review mouse interaction proposal
- [ ] Implement new mouse interaction
- [ ] Authoring Tool Mouse events request:
![image](https://user-images.githubusercontent.com/4562825/158266005-0b2f0e71-dc0b-425e-ad05-22584557dbf3.png)
User Stories with more Keyboard events: https://docs.google.com/spreadsheets/d/1mskEYpP3oNgs9Gvw4BQXJ3hPbBlTULZWyHUH3MVhPxs/edit#gid=0

**Comment by enicolasgomez** [comment]
@jrmartin been looking at possible options and I think that the most robust interface for handling 3d objects right now is Adobe 3D Studio, they have a bunch of documentation. 

Found this video really useful to get some ideas:
https://www.youtube.com/watch?v=_xg8y-8WGhc

Here's a list of the main keyboard binding for scenes manipulation:

--Undo + Redo--
Ctrl+Z : Undo Scene 
Ctrl+Y : Redo Scene 
Shift+Z : Undo Viewport 
Shift+Y : Redo Viewport

--Main Tools--
Q : Selection Object
W : Move Tool
E : Rotation Tool
R : Scale Tool

--Views--
B : Bottom
T : Top
L : Left: 
F : Front 
P : Perspective View
D : Disable Viewport
Alt+W : Maximize View

--Zoom--
Alt+Z : Zoom Mode 
Ctrl – : Zoom Out 
Ctrl + : Zoom In

--Viewport Toggle--
Alt+X : Display See-Through
F3 : Toggle Wireframe Mode
F4 : Toggle Edge Face Mode
F5 : Highlight X Axis
F6 : Highlight Y Axis
F7 : Highlight Z Axis 
Alt+Q : Isolate Selection
Ctrl+C : Make Camera on view
Ctrl+V : Make copy/ instance or hold down Shift + Drag 

--Selection--
Page Up : Select Parent
Page Down : Select Child
Ctrl+A : Select All

--Align + Snap--
A : Angle Snap tool
Alt+A : Align Tool
Shift+A : Quick Align

**Comment by jrmartin** [comment]
Keep existing bindings plus introduce blender bindings for new ones. 
Look into doing bundle presets.

**Comment by enicolasgomez** [comment]
@jrmartin this is a starter on what could be implemented, anything else from the initial proposal was not possible to implement as-is. I think we can hear from them what they are really interested to implement after using the initial version:


![Screen Shot 2022-03-28 at 11.45.57.png](https://images.zenhubusercontent.com/610183f51ec1245011ca9923/db6f57d8-826b-4e0a-a953-569d6531b4b6)
