### ISSUE TITLE
3D Scene consuming 100% CPU resources

### ISSUE THREAD

**Issue by enicolasgomez** [MetaCell/open-physiology-viewer#31]
![image.png](https://images.zenhubusercontent.com/610183f51ec1245011ca9923/24812f09-a7da-47f2-a178-1e117f4a30fc)

3d web scene keeps re-rendering without having any model update:

https://threejsfundamentals.org/threejs/lessons/threejs-rendering-on-demand.html

I have also noticed that there's not GPU usage but that could be a WebGL configuration on my side. Need to do more research.

**Comment by zsinnema** [comment]
Hi @enicolasgomez , yes I know. Imo you should search somewhere in the mouse hovering function.... please go ahead with this

**Comment by enicolasgomez** [comment]
@zsinnema 

this was related to `window.requestAnimationFrame` being called in a closed loop by `animate`
now animate expects a render boolean which defaults to false, preventing unnecessary processing when the design is not updated.

Also, animate has been attached to common canvas events (e.g. focus) which is called with the new parameter set to true.

The FPS has not been compromised.

If we are ok with this approach, I will connect the tool tip menu and other events that would need refreshing on the webGLScene.

**Comment by zsinnema** [comment]
hi @enicolasgomez sounds good, can you push a commit so I can see how you implemented/would like to implement this? thanks

**Comment by enicolasgomez** [comment]
@zsinnema 

https://github.com/MetaCell/open-physiology-viewer/blob/5a1c3cb946329e198027cb2c5ce563afb5480953/src/components/webGLScene.js#L286

**Comment by zsinnema** [comment]
@enicolasgomez after reading this: https://threejs.org/docs/#manual/en/introduction/Creating-a-scene
i do think your solution y/n running the animate function isn't the correct solution
e.g. if you look at this demo: https://jsfiddle.net/fxurzeb4/ ,with the animate function called in a loop, it's not eating up your cpu

**Comment by enicolasgomez** [comment]
putting some information together about my findings so far:

![image](https://user-images.githubusercontent.com/5366927/128539645-d76b4fe5-44b5-4635-98c8-968bb4fc9791.png)

seems like angula relies on zonejs which is a is an execution context that persists across async tasks, while looking at performance profiler on chrome it looks like it's the one hitting requestAnimationFrame aggressively, here's some documentation and possible solutions that I found while researching:

https://github.com/angular/angular/issues/8804#issuecomment-221456326

this one is specific reported for ThreeJS

https://github.com/angular/zone.js/issues/393

**Comment by zsinnema** [comment]
see also https://discourse.threejs.org/t/angular-12-threejs/2739/3

**Comment by enicolasgomez** [comment]
On this approach I have added an orbit control listener on `change` event to fire up the animation cycle:

```
        this.controls.addEventListener('change', () => {
          window.requestAnimationFrame(() => this.animate());
        });
```

I have also added calls to animate when the graph is updated or when the window is resized.

So far, the only functionality missing is after loading a new graph (at init or while using the app), there doesn't seem to be a staight forward way to attach the animate call to a complete event when the scene has completed loading the graph.

Still looking into this.

**Comment by zsinnema** [comment]
I'm not sure this is the way to go....
you are trying to catch all events that cause updates to the scene and then call the render.
what if you/we miss events? or when we add new elements and don't implement the change event for rerendering...

basically the question is: how do we know that the scene is changed without implementing onchange handlers on every element/object

if we solve this then we can render (update) the scene on demand

**Comment by enicolasgomez** [comment]
Not all events, these three should be enough as any other tool will end up calling any of these (e.g. zoom ends up using orbit)

- window resize event
- orbit control change event
- loading a new graph

the problem is with #3, according to threejs, any Object3D object should fire a `onAfterRender` event which for some reason ThreeForceGraph is not doing - while it should:

```
        this.graph.onAfterRender(()=>{
          this.animate();
        });
```

https://threejs.org/docs/#api/en/core/Object3D.onAfterRender

this approach, for any other object different than ThreeForceGraph is widely validated all over the web and for my own validation everything is working plus the CPU usage has been dramatically reduced; except from the `onAfterRender` event not being fired, anything else seems to be behaving correctly.

I think what you say about firing a single event when the scene changes could work too, will go over gepetto to see what it's doing.

**Comment by zsinnema** [comment]
> Not all events, these three should be enough as any other tool will end up calling any of these (e.g. zoom ends up using orbit)
> 
> * window resize event
> * orbit control change event
> * loading a new graph
> 
> the problem is with #3, according to threejs, any Object3D object should fire a `onAfterRender` event which for some reason ThreeForceGraph is not doing - while it should:
> 
> ```
>         this.graph.onAfterRender(()=>{
>           this.animate();
>         });
> ```
> 
> https://threejs.org/docs/#api/en/core/Object3D.onAfterRender
> 
> this approach, for any other object different than ThreeForceGraph is widely validated all over the web and for my own validation everything is working plus the CPU usage has been dramatically reduced; except from the `onAfterRender` event not being fired, anything else seems to be behaving correctly. Here's an exact description of the problem:
> 
> https://stackoverflow.com/questions/27318854/three-js-static-scene-detect-when-webgl-render-is-complete
> 
> I think what you say about detecting the single firing event when the scene changes could work but it's not only about changing the scene but catching the event in which it finished rendering; so i think we are on the same page.

sounds like a nice solution except the onAfterRender not being called. Do you have a working demo?

**Comment by enicolasgomez** [comment]
@zsinnema yes, I pushed the code to the branch. About the skipRender hack, I rather pass on that implementation by now (in the other hand for sure it's going to achieve a lowerer CPU usage). In my previous attempt, everything else except from onAfterRender is working (while it should). Will come back later to this.

**Comment by zsinnema** [comment]
imo we should implement both :-)
while your solution is keeping the cpu down by not rendering, my solution limits the amount of renders
when the scene is complex and we want to move the scene around rendering too many renders will burn the cpu and there will be stuttering

**Comment by enicolasgomez** [comment]
it looks like they are not implementing a `onAfterRender` event as defined on threeJS implementation but while looking at the TheeForceGraph prototype it seems that it exposes `onFinishLoading`. Fortunately, this works the same as onAfterRender and now the model is rendering after loading.

I'll keep doing some testing and add your stuttering implementation but so far this seems to work well.

**Comment by enicolasgomez** [comment]
@jrmartin @zsinnema 

I have just pushed a final version which seems to be working. Please review that there isn't anything missing or not working as expected: Changes so far:

- animationFrame constant loop pattern has been disabled from `animate()` considering that such a pattern is proper for a constant animation scene, like a video game or a physics engine.

instead, rendering is fired on demand on the following events

- window resize event
- orbit control change event
- loading a new graph

as a side note, for item #3, TheeForceGraph implements ThreeJS::3DObject which is supposed to be firing a `onFinishLoading` event, which isn't. After reviewing it's prototype it's been found that a similar `onFinishLoading` is fired from this object and this has been used to subscribe and fire the rendering event.

Any other tool will end up using any of the above 3 meta-events (take a zoom control e.g. or the label size widget).

as an other side note, a `skipRender` mechanism proposed by @zsinnema has been implemented. I left that commented out so far as I couldn't test it against any big enough model and the timer would need some proper tuning, as far as I've tested it reduced the FPS for small models.

Please let me know how it goes on your side. Thanks.

**Comment by jrmartin** [comment]
Hi @enicolasgomez. Tom reported an issue after testing this branch. We'll need to revisit this and find out what's going on with those frame rates. 

https://github.com/tgbugs/open-physiology-viewer/pull/1
