### ISSUE TITLE
TOO Map: Make regions, wires, lyphs and other objects easier to select

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/open-physiology-viewer#40]

**Comment by enicolasgomez** [comment]
@jrmartin @vidhya-metacell if you import this super simple model I was able to create to replicate the issue, you will see that 

`{
  "id"  : "jointTreesAtSoma",
  "name": "Omega trees joint at Soma",
  "description": "Demo model with two generated omega trees connected to a common lyph",
  "author": "Natallia Kokash",
  "nodes": [
    {
      "id": "n1"
    },
    {
      "id": "n2"
    }
  ]
}`

As you can see in the video the raytracing returns an array everytime the mouse is hovered in any of the two objects, so it's not a selection issue what's taking place but a object indentification issue within the ray traced objects, this is IMO the part that fails:

https://github.com/MetaCell/open-physiology-viewer/blob/master/src/components/webGLScene.js#L550

according to the intersectObject documentation:
https://threejs.org/docs/#api/en/core/Raycaster

"Checks all intersection between the ray and the object with or without the descendants. Intersections are returned sorted by distance, closest first."

it makes sense that it's pulling inex 0 from the Array (closest), I think we just need to give some context to what context is in this case. Will take a look at it further.

Once this is fixed then we can take a look at what's still failing for real low width objects like wires, maybe we see some improvements there too.

https://user-images.githubusercontent.com/5366927/137558448-d1ff1709-bd1d-4ca3-902e-0ef0ea8240fc.mp4
