### ISSUE TITLE
Understand ApiNATOMY Code Data

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/open-physiology-viewer#44]
Goal of this card is to understand how we are reading the connectivity model from the json file .

How do we create the scaffold TOO Map from the json with regions and wires? How do we create the Lyphs ?
How are we extracting the position of the lyphs? Position of the scaffold regions and wires?
How is the current application handling the rendering of these objects?

The main use case we are working on :
1 ) Load TOO Map with scaffold regions and wires
2) Load connectivity model
3) Remove scaffold wires and regions from TOO Map, if not referenced inside the connectivity model by 'hostedBy' and 'wiredTo'.

List of resources
https://docs.google.com/document/d/1XWk_XjTKnw7eKm3_sdDc2aGZ2lpeIhVaWInhVhmuxdg/edit

**Comment by jrmartin** [comment]
@enicolasgomez This is the json file we can use to test the physiology viewer. 

https://scicrunch.slack.com/files/U085FF4TF/F02CZFZLUHY/dev-layout-conn-model.json

**Comment by enicolasgomez** [comment]
For own reference, diagram location:
https://lucid.app/lucidchart/54a2a39d-aba3-4afd-90d0-a4eefd58ccc4

will share to Jesus and Zoran when finished the initial phase
