### ISSUE TITLE
Explore Alternative to d3-force Library

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/open-physiology-viewer#45]
Now that issue #44 is done and we understand the code better, we need to understand if the use of the d3-force library is necessary and/or if there are alternatives that work better. 

The goal of this card is to explore other libraries that can do what we need.

Full list of requirements related to the TOO Map Layout and Canvas https://docs.google.com/document/u/1/d/1n1jyIq6WT9S-FbY_DAP52iWZFyU3HFBydrS9UiV9oEI/edit

Goals:
1) What other libraries can we use instead of d3-force to accomplish what we need?
2) If we stick with d3-force, can we control the library forces to do what we need?
3) If we don't use d3-force, how do we keep Lyphs inside Regions and prevent them from leaving the regions? Also how do we keep the regions inside the TOO Map?

**Comment by enicolasgomez** [comment]
Some preliminar candidates:

Do we need 3D? Do we need forces?

https://visjs.org/
https://visjs.github.io/vis-graph3d/examples/index.html
http://sigmajs.org/
https://github.com/anvaka/VivaGraphJS
https://observablehq.com/@d3/d3-packenclose
https://github.com/anvaka/ngraph
https://github.com/Niekes/d3-3d
