### ISSUE TITLE
Resizing TOO Map outer circles doesn't work

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/open-physiology-viewer#86]
If you try to resize the outer circles of the TOO Map by dragging the nodes, it doesn't work anymore. 

https://user-images.githubusercontent.com/4562825/145909639-1fea8db5-5ae4-4551-a53f-86addc2c0123.mp4

**Comment by enicolasgomez** [comment]
Noticed two things here so far:

https://github.com/MetaCell/open-physiology-viewer/blob/demo/src/view/render/threeForceGraphKapsule.js#L89

in here, for Anchor dragging, the position was the same so the delta was 0. I fixed that but adding an intermediate position field for drag event.

That didn't fix it so far, also noticed that inside relocate:
https://github.com/MetaCell/open-physiology-viewer/blob/demo/src/view/anchor.js#L29

this.layout is undefined.

Need to keep looking into it.
