### ISSUE TITLE
Autosizelyph() making inner lyphs too big

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/open-physiology-viewer#87]
Use branch 'inner-lyph-wire-transform'.
Toggle all groups ( or if just want to toggle one group, toggle group 'brain-regions group'.
- Inner lyphs are becoming larger than their parent lyphs. In screenshot below, the blue rectangle is Lyph with id "201", named 'Hypothalamus'. That lyph should be an inner lyph of the Diencephalon Lyph.
![image](https://user-images.githubusercontent.com/4562825/146081851-a6a26bc4-fa4c-4ff8-989d-42a21406d4e1.png)

**Comment by enicolasgomez** [comment]
@jrmartin couldn't replicate this one on that branch - can you verify and provide me with some more steps please?
